name: update README.md

on:
  schedule:
    - cron: '0 12 * * 4' # 매주 목요일 21:00 (한국 시간 = UTC +9:00)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }} 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run problem_generator.py
        run: |
          python3 problem_generator.py
      - name: Commit changes
        run: |
          git config --global user.name 'pushedrumex'
          git config --global user.email 'pushedrumex@naver.com'
          git add -A
          git commit -am "auto update README.md"
      - name: Push changes
        run: |
          git push origin main